#ifndef _ALTERA_HPS_0_BRIDGES_H_
#define _ALTERA_HPS_0_BRIDGES_H_

/*
 * This file was automatically generated by the swinfo2header utility.
 * 
 * Created from SOPC Builder system 'karaoke_soc' in
 * file 'Karaoke/hw/quartus/karaoke_soc.swinfo'.
 */

/*
 * This file contains macros for module 'hps_0_bridges' and devices
 * connected to the following masters:
 *   axi_f2h
 *   h2f_lw
 * 
 * Do not include this header file and another header file created for a
 * different module or master group at the same time.
 * Doing so may result in duplicate macro names.
 * Instead, use the system header file which has macros with unique names.
 */

/*
 * Macros for device 'video_character_buffer_with_dma_0_avalon_char_buffer_slave', class 'altera_up_avalon_video_character_buffer_with_dma'
 * The macros are prefixed with 'VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_BUFFER_SLAVE_'.
 * The prefix is the slave descriptor.
 */
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_BUFFER_SLAVE_COMPONENT_TYPE altera_up_avalon_video_character_buffer_with_dma
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_BUFFER_SLAVE_COMPONENT_NAME video_character_buffer_with_dma_0
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_BUFFER_SLAVE_BASE 0x0
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_BUFFER_SLAVE_SPAN 8192
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_BUFFER_SLAVE_END 0x1fff

/*
 * Macros for device 'mailbox_simple_0', class 'altera_avalon_mailbox_simple'
 * The macros are prefixed with 'MAILBOX_SIMPLE_0_'.
 * The prefix is the slave descriptor.
 */
#define MAILBOX_SIMPLE_0_COMPONENT_TYPE altera_avalon_mailbox_simple
#define MAILBOX_SIMPLE_0_COMPONENT_NAME mailbox_simple_0
#define MAILBOX_SIMPLE_0_BASE 0x2000
#define MAILBOX_SIMPLE_0_SPAN 16
#define MAILBOX_SIMPLE_0_END 0x200f

/*
 * Macros for device 'audio_and_video_config_0', class 'altera_up_avalon_audio_and_video_config'
 * The macros are prefixed with 'AUDIO_AND_VIDEO_CONFIG_0_'.
 * The prefix is the slave descriptor.
 */
#define AUDIO_AND_VIDEO_CONFIG_0_COMPONENT_TYPE altera_up_avalon_audio_and_video_config
#define AUDIO_AND_VIDEO_CONFIG_0_COMPONENT_NAME audio_and_video_config_0
#define AUDIO_AND_VIDEO_CONFIG_0_BASE 0x2010
#define AUDIO_AND_VIDEO_CONFIG_0_SPAN 16
#define AUDIO_AND_VIDEO_CONFIG_0_END 0x201f

/*
 * Macros for device 'video_character_buffer_with_dma_0_avalon_char_control_slave', class 'altera_up_avalon_video_character_buffer_with_dma'
 * The macros are prefixed with 'VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_CONTROL_SLAVE_'.
 * The prefix is the slave descriptor.
 */
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_CONTROL_SLAVE_COMPONENT_TYPE altera_up_avalon_video_character_buffer_with_dma
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_CONTROL_SLAVE_COMPONENT_NAME video_character_buffer_with_dma_0
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_CONTROL_SLAVE_BASE 0x2020
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_CONTROL_SLAVE_SPAN 8
#define VIDEO_CHARACTER_BUFFER_WITH_DMA_0_AVALON_CHAR_CONTROL_SLAVE_END 0x2027

/*
 * Macros for device 'Mixer_0_SD_Right', class 'Mixer'
 * The macros are prefixed with 'MIXER_0_SD_RIGHT_'.
 * The prefix is the slave descriptor.
 */
#define MIXER_0_SD_RIGHT_COMPONENT_TYPE Mixer
#define MIXER_0_SD_RIGHT_COMPONENT_NAME Mixer_0
#define MIXER_0_SD_RIGHT_BASE 0x2028
#define MIXER_0_SD_RIGHT_SPAN 2
#define MIXER_0_SD_RIGHT_END 0x2029

/*
 * Macros for device 'Mixer_0_SD_Left', class 'Mixer'
 * The macros are prefixed with 'MIXER_0_SD_LEFT_'.
 * The prefix is the slave descriptor.
 */
#define MIXER_0_SD_LEFT_COMPONENT_TYPE Mixer
#define MIXER_0_SD_LEFT_COMPONENT_NAME Mixer_0
#define MIXER_0_SD_LEFT_BASE 0x202a
#define MIXER_0_SD_LEFT_SPAN 2
#define MIXER_0_SD_LEFT_END 0x202b


#endif /* _ALTERA_HPS_0_BRIDGES_H_ */
