# TCL File Generated by Component Editor 15.1
# Sun May 29 20:12:33 CEST 2016
# DO NOT MODIFY


# 
# Mixer "Mixer" v1.0
#  2016.05.29.20:12:33
# 
# 

# 
# request TCL package from ACDS 15.1
# 
package require -exact qsys 15.1


# 
# module Mixer
# 
set_module_property DESCRIPTION ""
set_module_property NAME Mixer
set_module_property VERSION 1.0
set_module_property INTERNAL false
set_module_property OPAQUE_ADDRESS_MAP true
set_module_property AUTHOR ""
set_module_property DISPLAY_NAME Mixer
set_module_property INSTANTIATE_IN_SYSTEM_MODULE true
set_module_property EDITABLE true
set_module_property REPORT_TO_TALKBACK false
set_module_property ALLOW_GREYBOX_GENERATION false
set_module_property REPORT_HIERARCHY false


# 
# file sets
# 
add_fileset QUARTUS_SYNTH QUARTUS_SYNTH "" ""
set_fileset_property QUARTUS_SYNTH TOP_LEVEL Mixer
set_fileset_property QUARTUS_SYNTH ENABLE_RELATIVE_INCLUDE_PATHS false
set_fileset_property QUARTUS_SYNTH ENABLE_FILE_OVERWRITE_MODE false
add_fileset_file Mixer.vhd VHDL PATH ../hdl/Mixer.vhd TOP_LEVEL_FILE


# 
# parameters
# 
add_parameter DATA_WIDTH NATURAL 16 ""
set_parameter_property DATA_WIDTH DEFAULT_VALUE 16
set_parameter_property DATA_WIDTH DISPLAY_NAME DATA_WIDTH
set_parameter_property DATA_WIDTH TYPE NATURAL
set_parameter_property DATA_WIDTH UNITS None
set_parameter_property DATA_WIDTH ALLOWED_RANGES 0:2147483647
set_parameter_property DATA_WIDTH DESCRIPTION ""
set_parameter_property DATA_WIDTH HDL_PARAMETER true


# 
# display items
# 


# 
# connection point clock
# 
add_interface clock clock end
set_interface_property clock clockRate 0
set_interface_property clock ENABLED true
set_interface_property clock EXPORT_OF ""
set_interface_property clock PORT_NAME_MAP ""
set_interface_property clock CMSIS_SVD_VARIABLES ""
set_interface_property clock SVD_ADDRESS_GROUP ""

add_interface_port clock clk clk Input 1


# 
# connection point reset
# 
add_interface reset reset end
set_interface_property reset associatedClock clock
set_interface_property reset synchronousEdges DEASSERT
set_interface_property reset ENABLED true
set_interface_property reset EXPORT_OF ""
set_interface_property reset PORT_NAME_MAP ""
set_interface_property reset CMSIS_SVD_VARIABLES ""
set_interface_property reset SVD_ADDRESS_GROUP ""

add_interface_port reset reset_n reset_n Input 1


# 
# connection point Mic_Left
# 
add_interface Mic_Left avalon_streaming end
set_interface_property Mic_Left associatedClock clock
set_interface_property Mic_Left associatedReset reset
set_interface_property Mic_Left dataBitsPerSymbol 8
set_interface_property Mic_Left errorDescriptor ""
set_interface_property Mic_Left firstSymbolInHighOrderBits true
set_interface_property Mic_Left maxChannel 0
set_interface_property Mic_Left readyLatency 0
set_interface_property Mic_Left ENABLED true
set_interface_property Mic_Left EXPORT_OF ""
set_interface_property Mic_Left PORT_NAME_MAP ""
set_interface_property Mic_Left CMSIS_SVD_VARIABLES ""
set_interface_property Mic_Left SVD_ADDRESS_GROUP ""

add_interface_port Mic_Left Audio_Mic_Left data Input data_width
add_interface_port Mic_Left Ready_Mic_Left ready Output 1
add_interface_port Mic_Left Valid_Mic_Left valid Input 1


# 
# connection point Mic_Right
# 
add_interface Mic_Right avalon_streaming end
set_interface_property Mic_Right associatedClock clock
set_interface_property Mic_Right associatedReset reset
set_interface_property Mic_Right dataBitsPerSymbol 8
set_interface_property Mic_Right errorDescriptor ""
set_interface_property Mic_Right firstSymbolInHighOrderBits true
set_interface_property Mic_Right maxChannel 0
set_interface_property Mic_Right readyLatency 0
set_interface_property Mic_Right ENABLED true
set_interface_property Mic_Right EXPORT_OF ""
set_interface_property Mic_Right PORT_NAME_MAP ""
set_interface_property Mic_Right CMSIS_SVD_VARIABLES ""
set_interface_property Mic_Right SVD_ADDRESS_GROUP ""

add_interface_port Mic_Right Audio_Mic_Right data Input data_width
add_interface_port Mic_Right Ready_Mic_Right ready Output 1
add_interface_port Mic_Right Valid_Mic_Right valid Input 1


# 
# connection point SD_Left
# 
add_interface SD_Left avalon end
set_interface_property SD_Left addressUnits WORDS
set_interface_property SD_Left associatedClock clock
set_interface_property SD_Left associatedReset reset
set_interface_property SD_Left bitsPerSymbol 8
set_interface_property SD_Left burstOnBurstBoundariesOnly false
set_interface_property SD_Left burstcountUnits WORDS
set_interface_property SD_Left explicitAddressSpan 0
set_interface_property SD_Left holdTime 0
set_interface_property SD_Left linewrapBursts false
set_interface_property SD_Left maximumPendingReadTransactions 0
set_interface_property SD_Left maximumPendingWriteTransactions 0
set_interface_property SD_Left readLatency 0
set_interface_property SD_Left readWaitTime 1
set_interface_property SD_Left setupTime 0
set_interface_property SD_Left timingUnits Cycles
set_interface_property SD_Left writeWaitTime 0
set_interface_property SD_Left ENABLED true
set_interface_property SD_Left EXPORT_OF ""
set_interface_property SD_Left PORT_NAME_MAP ""
set_interface_property SD_Left CMSIS_SVD_VARIABLES ""
set_interface_property SD_Left SVD_ADDRESS_GROUP ""

add_interface_port SD_Left Audio_SD_Left writedata Input data_width
add_interface_port SD_Left Write_SD_Left write Input 1
add_interface_port SD_Left WaitRequest_SD_Left waitrequest Output 1
set_interface_assignment SD_Left embeddedsw.configuration.isFlash 0
set_interface_assignment SD_Left embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment SD_Left embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment SD_Left embeddedsw.configuration.isPrintableDevice 0


# 
# connection point SD_Right
# 
add_interface SD_Right avalon end
set_interface_property SD_Right addressUnits WORDS
set_interface_property SD_Right associatedClock clock
set_interface_property SD_Right associatedReset reset
set_interface_property SD_Right bitsPerSymbol 8
set_interface_property SD_Right burstOnBurstBoundariesOnly false
set_interface_property SD_Right burstcountUnits WORDS
set_interface_property SD_Right explicitAddressSpan 0
set_interface_property SD_Right holdTime 0
set_interface_property SD_Right linewrapBursts false
set_interface_property SD_Right maximumPendingReadTransactions 0
set_interface_property SD_Right maximumPendingWriteTransactions 0
set_interface_property SD_Right readLatency 0
set_interface_property SD_Right readWaitTime 1
set_interface_property SD_Right setupTime 0
set_interface_property SD_Right timingUnits Cycles
set_interface_property SD_Right writeWaitTime 0
set_interface_property SD_Right ENABLED true
set_interface_property SD_Right EXPORT_OF ""
set_interface_property SD_Right PORT_NAME_MAP ""
set_interface_property SD_Right CMSIS_SVD_VARIABLES ""
set_interface_property SD_Right SVD_ADDRESS_GROUP ""

add_interface_port SD_Right Audio_SD_Right writedata Input data_width
add_interface_port SD_Right Write_SD_Right write Input 1
add_interface_port SD_Right WaitRequest_SD_Right waitrequest Output 1
set_interface_assignment SD_Right embeddedsw.configuration.isFlash 0
set_interface_assignment SD_Right embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment SD_Right embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment SD_Right embeddedsw.configuration.isPrintableDevice 0


# 
# connection point Mix_Left
# 
add_interface Mix_Left avalon_streaming start
set_interface_property Mix_Left associatedClock clock
set_interface_property Mix_Left associatedReset reset
set_interface_property Mix_Left dataBitsPerSymbol 8
set_interface_property Mix_Left errorDescriptor ""
set_interface_property Mix_Left firstSymbolInHighOrderBits true
set_interface_property Mix_Left maxChannel 0
set_interface_property Mix_Left readyLatency 0
set_interface_property Mix_Left ENABLED true
set_interface_property Mix_Left EXPORT_OF ""
set_interface_property Mix_Left PORT_NAME_MAP ""
set_interface_property Mix_Left CMSIS_SVD_VARIABLES ""
set_interface_property Mix_Left SVD_ADDRESS_GROUP ""

add_interface_port Mix_Left Audio_Mix_Left data Output data_width
add_interface_port Mix_Left Ready_Mix_Left ready Input 1
add_interface_port Mix_Left Valid_Mix_Left valid Output 1


# 
# connection point Mix_Right
# 
add_interface Mix_Right avalon_streaming start
set_interface_property Mix_Right associatedClock clock
set_interface_property Mix_Right associatedReset reset
set_interface_property Mix_Right dataBitsPerSymbol 8
set_interface_property Mix_Right errorDescriptor ""
set_interface_property Mix_Right firstSymbolInHighOrderBits true
set_interface_property Mix_Right maxChannel 0
set_interface_property Mix_Right readyLatency 0
set_interface_property Mix_Right ENABLED true
set_interface_property Mix_Right EXPORT_OF ""
set_interface_property Mix_Right PORT_NAME_MAP ""
set_interface_property Mix_Right CMSIS_SVD_VARIABLES ""
set_interface_property Mix_Right SVD_ADDRESS_GROUP ""

add_interface_port Mix_Right Audio_Mix_Right data Output data_width
add_interface_port Mix_Right Valid_Mix_Right valid Output 1
add_interface_port Mix_Right Ready_Mix_Right ready Input 1


# 
# connection point avalon_slave_0
# 
add_interface avalon_slave_0 avalon end
set_interface_property avalon_slave_0 addressUnits WORDS
set_interface_property avalon_slave_0 associatedClock clock
set_interface_property avalon_slave_0 associatedReset reset
set_interface_property avalon_slave_0 bitsPerSymbol 8
set_interface_property avalon_slave_0 burstOnBurstBoundariesOnly false
set_interface_property avalon_slave_0 burstcountUnits WORDS
set_interface_property avalon_slave_0 explicitAddressSpan 0
set_interface_property avalon_slave_0 holdTime 0
set_interface_property avalon_slave_0 linewrapBursts false
set_interface_property avalon_slave_0 maximumPendingReadTransactions 0
set_interface_property avalon_slave_0 maximumPendingWriteTransactions 0
set_interface_property avalon_slave_0 readLatency 0
set_interface_property avalon_slave_0 readWaitTime 1
set_interface_property avalon_slave_0 setupTime 0
set_interface_property avalon_slave_0 timingUnits Cycles
set_interface_property avalon_slave_0 writeWaitTime 0
set_interface_property avalon_slave_0 ENABLED true
set_interface_property avalon_slave_0 EXPORT_OF ""
set_interface_property avalon_slave_0 PORT_NAME_MAP ""
set_interface_property avalon_slave_0 CMSIS_SVD_VARIABLES ""
set_interface_property avalon_slave_0 SVD_ADDRESS_GROUP ""

add_interface_port avalon_slave_0 AS_Add address Input 1
add_interface_port avalon_slave_0 AS_Wr write Input 1
add_interface_port avalon_slave_0 AS_WrData writedata Input 32
add_interface_port avalon_slave_0 AS_Rd read Input 1
add_interface_port avalon_slave_0 AS_RdData readdata Output 32
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isFlash 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isMemoryDevice 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isNonVolatileStorage 0
set_interface_assignment avalon_slave_0 embeddedsw.configuration.isPrintableDevice 0

